version: 0.0
os: linux
files:
  - source: /
    destination: /root/go/src/github.com/herdius/herdius-blockchain-api
    overwrite: true
permissions:
  - object: /root/go/src/github.com/herdius/herdius-blockchain-api/deployment
    pattern: "**"
    mode: 755
hooks:
  AfterInstall:
     - location: deployment/start_server.sh
       timeout: 60
       runas: root
