// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/message.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Timestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int64    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8368f5d77b0b9b7b, []int{0}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int64 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type BlockHeightRequest struct {
	BlockHeight          int64    `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeightRequest) Reset()         { *m = BlockHeightRequest{} }
func (m *BlockHeightRequest) String() string { return proto.CompactTextString(m) }
func (*BlockHeightRequest) ProtoMessage()    {}
func (*BlockHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8368f5d77b0b9b7b, []int{1}
}

func (m *BlockHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeightRequest.Unmarshal(m, b)
}
func (m *BlockHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeightRequest.Marshal(b, m, deterministic)
}
func (m *BlockHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeightRequest.Merge(m, src)
}
func (m *BlockHeightRequest) XXX_Size() int {
	return xxx_messageInfo_BlockHeightRequest.Size(m)
}
func (m *BlockHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeightRequest proto.InternalMessageInfo

func (m *BlockHeightRequest) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type BlockResponse struct {
	BlockHeight int64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Time of block intialization
	Time         *Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Transactions int32      `protobuf:"varint,3,opt,name=transactions,proto3" json:"transactions,omitempty"`
	// Supervisor herdius token address who created the block
	SupervisorAddress    string   `protobuf:"bytes,4,opt,name=supervisor_address,json=supervisorAddress,proto3" json:"supervisor_address,omitempty"`
	StateRoot            []byte   `protobuf:"bytes,5,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8368f5d77b0b9b7b, []int{2}
}

func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (m *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(m, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *BlockResponse) GetTime() *Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *BlockResponse) GetTransactions() int32 {
	if m != nil {
		return m.Transactions
	}
	return 0
}

func (m *BlockResponse) GetSupervisorAddress() string {
	if m != nil {
		return m.SupervisorAddress
	}
	return ""
}

func (m *BlockResponse) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "protobuf.Timestamp")
	proto.RegisterType((*BlockHeightRequest)(nil), "protobuf.BlockHeightRequest")
	proto.RegisterType((*BlockResponse)(nil), "protobuf.BlockResponse")
}

func init() { proto.RegisterFile("protobuf/message.proto", fileDescriptor_8368f5d77b0b9b7b) }

var fileDescriptor_8368f5d77b0b9b7b = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x86, 0xe5, 0xaf, 0xed, 0x07, 0xbd, 0x86, 0xa1, 0x06, 0x21, 0x2f, 0x48, 0x21, 0x0b, 0x59,
	0x1a, 0x24, 0x18, 0x18, 0x98, 0xe8, 0xd4, 0xb1, 0xb2, 0x98, 0x58, 0x2a, 0x27, 0x39, 0x5a, 0x0b,
	0xe2, 0x0b, 0x3e, 0x87, 0x7f, 0xc9, 0x7f, 0x42, 0x75, 0x48, 0x2b, 0x36, 0x36, 0x3f, 0xcf, 0xdd,
	0x59, 0xf7, 0x1e, 0x5c, 0xb6, 0x9e, 0x02, 0x95, 0xdd, 0xeb, 0x6d, 0x83, 0xcc, 0x66, 0x8b, 0x45,
	0x14, 0xf2, 0x74, 0xf0, 0xd9, 0x23, 0x4c, 0x9f, 0x6d, 0x83, 0x1c, 0x4c, 0xd3, 0x4a, 0x05, 0x27,
	0x8c, 0x15, 0xb9, 0x9a, 0x95, 0x48, 0x45, 0x3e, 0xd2, 0x03, 0xca, 0x0b, 0x98, 0x38, 0xe3, 0x88,
	0xd5, 0xbf, 0xe8, 0x7b, 0xc8, 0x1e, 0x40, 0x2e, 0xdf, 0xa9, 0x7a, 0x5b, 0xa1, 0xdd, 0xee, 0x82,
	0xc6, 0x8f, 0x0e, 0x39, 0xc8, 0x6b, 0x48, 0xca, 0xbd, 0xdd, 0xec, 0xa2, 0xfe, 0xf9, 0x6a, 0x56,
	0x1e, 0x3b, 0xb3, 0x2f, 0x01, 0x67, 0x71, 0x52, 0x23, 0xb7, 0xe4, 0x18, 0xff, 0x30, 0x24, 0x6f,
	0x60, 0x1c, 0x6c, 0x83, 0x71, 0x85, 0xd9, 0xdd, 0x79, 0x31, 0x64, 0x28, 0x0e, 0x01, 0x74, 0x6c,
	0x90, 0x19, 0x24, 0xc1, 0x1b, 0xc7, 0xa6, 0x0a, 0x96, 0x1c, 0xab, 0x51, 0x2a, 0xf2, 0x89, 0xfe,
	0xe5, 0xe4, 0x02, 0x24, 0x77, 0x2d, 0xfa, 0x4f, 0xcb, 0xe4, 0x37, 0xa6, 0xae, 0x3d, 0x32, 0xab,
	0x71, 0x2a, 0xf2, 0xa9, 0x9e, 0x1f, 0x2b, 0x4f, 0x7d, 0x41, 0x5e, 0x01, 0x70, 0x30, 0x01, 0x37,
	0x9e, 0x28, 0xa8, 0x49, 0x2a, 0xf2, 0x44, 0x4f, 0xa3, 0xd1, 0x44, 0x61, 0xb9, 0x80, 0x79, 0x45,
	0x4d, 0xb1, 0x43, 0x5f, 0xdb, 0x8e, 0xfb, 0xcd, 0x96, 0xc9, 0xaa, 0xc7, 0xf5, 0x9e, 0xd6, 0xe2,
	0xe5, 0x70, 0xf4, 0xf2, 0x7f, 0x7c, 0xdd, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xf5, 0x27,
	0xaf, 0x9f, 0x01, 0x00, 0x00,
}
