[dev]
supervisorhost      = "127.0.0.1"
supervisorport      = 3000
tcp                 = "tcp"
connectionport      = 5555
selfip              = "localhost"

[staging]
supervisorhost      = "10.0.1.159"
supervisorport      = 3000
tcp                 = "tcp"
connectionport      = 5555
selfip              = "10.0.0.34"
